### ISSUE TITLE
Dataset structure table poorly formated

### ISSUE THREAD

**Issue by ToonTalk** [ox-it/LiveData_htmlwidgets#11]
The datasets that this tutorial considers are structured as follows:

![image](https://cloud.githubusercontent.com/assets/2138696/17485350/5884eb4e-5d85-11e6-9a87-adb95abca75b.png)

The spacing between columns 1 and 2 is much too little.

**Comment by charliejhadley** [comment]
Agreed - let's quote the measure column to force the alignment to look nice (as people won't see the code in the tutorial anyhow)

**Comment by charliejhadley** [comment]
Fixed in: https://github.com/ox-it/OxfordIDN_htmlwidgets/commit/8af201f8437482afb6c5b87b27c8ba9e12e0e6fd
