### ISSUE TITLE
Code fragments need comments

### ISSUE THREAD

**Issue by ToonTalk** [ox-it/LiveData_htmlwidgets#2]
But not too many. E.g. in http://ox-it.github.io/LiveData_htmlwidgets/charts/BarCharts/ there is

desktopItems <- read.csv(file = "https://ndownloader.figshare.com/files/5360960")
knitr::kable(head(desktopItems))

I think the first line is self-evident so I recommend changing it to

desktopItems <- read.csv(file = "https://ndownloader.figshare.com/files/5360960")
// after reading the CSV file blah blah blah ...
knitr::kable(head(desktopItems))

**Comment by charliejhadley** [comment]
The initial concern has been addressed, regarding `kable`. https://github.com/ox-it/OxfordIDN_htmlwidgets/issues/45
