### ISSUE TITLE
Replace replicated code with 'for' loop in StackedBarCharts

### ISSUE THREAD

**Issue by ToonTalk** [ox-it/LiveData_htmlwidgets#22]
Repeated code is harder to read and doesn't scale. The following should be clearer as a loop.

  hc_add_series(name = measure_columns[1],
                data = stacked_bar_chart_df[,measure_columns[1]]) %>%
  hc_add_series(name = measure_columns[2],
                data = stacked_bar_chart_df[,measure_columns[2]]) %>%
  hc_add_series(name = measure_columns[3],
                data = stacked_bar_chart_df[,measure_columns[3]]) %>%
  hc_add_series(name = measure_columns[4],
                data = stacked_bar_chart_df[,measure_columns[4]]) %>%
  hc_add_series(name = measure_columns[5],
                data = stacked_bar_chart_df[,measure_columns[5]]) %>%

**Comment by charliejhadley** [comment]
We've discussed in meatspace and have agreed a compromise
