### ISSUE TITLE
The wisdom of adding datatype to variable names

### ISSUE THREAD

**Issue by ToonTalk** [ox-it/LiveData_htmlwidgets#23]
E.g. stacked_bar_chart_df versus stacked_bar_chart

See https://en.wikipedia.org/wiki/Hungarian_notation#Disadvantages

though there is

https://en.wikipedia.org/wiki/Hungarian_notation#Advantages

Personally I'm not a fan but maybe should depend on what is most common in R code.

**Comment by charliejhadley** [comment]
Good point - have changed for here, will keep in mind everywhere but remind me 👍
