### ISSUE TITLE
Reduce repeating code in StackedBarCharts

### ISSUE THREAD

**Issue by ToonTalk** [ox-it/LiveData_htmlwidgets#25]
E.g. Normal Stacking repeats much of previous code sample. Harder to read since need to check the first two expressions are the same. Wouldn't it be better to just show the changed expression and mention in the text that the rest is unchanged?

**Comment by ToonTalk** [comment]
As was done later with

generated_chart %>%
  hc_legend(reversed = TRUE)

but shouldn't that include 

generated_chart %>%
  hc_chart(type = "bar") %>%
  hc_plotOptions(series = list(stacking = "normal"))

?

**Comment by charliejhadley** [comment]
We discussed this and decided it was ok this one time
