### ISSUE TITLE
Questions about Functionalised Stacked Barchart

### ISSUE THREAD

**Issue by ToonTalk** [ox-it/LiveData_htmlwidgets#29]
Is stacked_hc_chart a good name?

hc doesn't mean much to most users does it?

And as abstraction it shouldn't matter how it was implemented - though I know that that isn't strictly true here since the interface of the charts does depend upon the library used.

Also if one doesn't want any ordering_function should one provide the identity function?

**Comment by charliejhadley** [comment]
Awesome - both of these have been addressed and a nice new name created.
