### ISSUE TITLE
Column names unclear -- needs more explanation

### ISSUE THREAD

**Issue by ToonTalk** [ox-it/LiveData_htmlwidgets#3]
E.g.

Linux   30.90909

in  http://ox-it.github.io/LiveData_htmlwidgets/charts/BarCharts/

Hard to understand what is going on here.

**Comment by ToonTalk** [comment]
Figured it out. Proposed clearer text in pull request.

**Comment by ToonTalk** [comment]
Or maybe not -- unclear about what eval is accomplishing.

**Comment by charliejhadley** [comment]
Superceded by https://github.com/ox-it/LiveData_htmlwidgets/issues/13
