### ISSUE TITLE
stacked_bar_chart should add a comment to the default ordering_function

### ISSUE THREAD

**Issue by ToonTalk** [ox-it/LiveData_htmlwidgets#32]
Later you do explain the c leaves the order unchanged but I think there should also be a comment about this in the function definition itself.

Also in the example application where ordering_function = var do nearly all readers know that 'var' is the variance function? If not another comment would help.

**Comment by charliejhadley** [comment]
Comment should be added, agreed

**Comment by charliejhadley** [comment]
Already fixed, don't have commit reference - though.
