### ISSUE TITLE
Strange URL style when hovering

### ISSUE THREAD

**Issue by ToonTalk** [ox-it/LiveData_htmlwidgets#43]
It looks like there are several links here:

![image](https://cloud.githubusercontent.com/assets/2138696/18432072/ff99fed4-78d7-11e6-8c88-75045818d70a.png)

Why aren't the spaces underlined so it is clear it is a single link?

In http://ox-it.github.io/OxfordIDN_htmlwidgets/datatable/

**Comment by charliejhadley** [comment]
Fixed in https://github.com/ox-it/OxfordIDN_htmlwidgets/commit/ff8266be22cc78582968d7c9cd4d8b9f3214966b
