### ISSUE TITLE
Comments needed in import data code 

### ISSUE THREAD

**Issue by ToonTalk** [ox-it/LiveData_htmlwidgets#45]
desktopItems <- read.csv(file = "https://ndownloader.figshare.com/files/5360960", stringsAsFactors = F)
knitr::kable(head(desktopItems))

What is 'F'?

Explain what 'knitr::kable(head(desktopItems))' accomplishes

In http://ox-it.github.io/OxfordIDN_htmlwidgets/datatable/

**Comment by charliejhadley** [comment]
Fix this with https://github.com/ox-it/OxfordIDN_htmlwidgets/issues/2

**Comment by charliejhadley** [comment]
Fixed in https://github.com/ox-it/OxfordIDN_htmlwidgets/commit/7e070c1b2fa87754fdce0440a7191e7d0848ac59
