### ISSUE TITLE
Confusion about the Plotly bar graph code

### ISSUE THREAD

**Issue by ToonTalk** [ox-it/LiveData_htmlwidgets#6]
It seems that unlike the highchart version here the x and y need to be swapped to make the horizontal version. Need to discuss this.

Why is the vertical version sorted unlike the vertical highchart version?

Also the introduction to the the highchart and plotly sections should say there are two recommended libraries - first we consider the one called highchart and then plotly (or something to that effect)

**Comment by charliejhadley** [comment]
Closed and will be addressed in https://github.com/ox-it/LiveData_htmlwidgets/issues/16
