### ISSUE TITLE
Table of desktop items could be improved

### ISSUE THREAD

**Issue by ToonTalk** [ox-it/LiveData_htmlwidgets#8]
I think the mean is confusing here. Why not something like

aggregate_function = sum

in http://ox-it.github.io/LiveData_htmlwidgets/charts/BarCharts/

**Comment by charliejhadley** [comment]
It's interesting to show the mean items per OS but not per University, instead the overall messiness (or some analog to it) can be shown by computing the "sum"..

So would call as:

``` r
intermediate_aggregate <- aggregate_data_for_barchart(
  data = desktopItems,
  dimension_column = "University",
  measure_column = "Desktop.Items",
  aggregate_function = sum
)
```

**Comment by charliejhadley** [comment]
Fix in https://github.com/ox-it/OxfordIDN_htmlwidgets/commit/8af201f8437482afb6c5b87b27c8ba9e12e0e6fd
